
import React from 'react';
import TextField from '@material-ui/core/TextField';
import Autocomplete from '@material-ui/lab/Autocomplete';
import handleInput from '../hooks/status';

const profession = [
  {
    'Id': 1,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración de servicios',
    'IdEducationLevel': 7,
    'VisibilityOrder': 11,
  },
  {
    'Id': 2,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración turística hotelera',
    'IdEducationLevel': 6,
    'VisibilityOrder': 19,
  },
  {
    'Id': 3,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Antropología',
    'IdEducationLevel': 6,
    'VisibilityOrder': 23,
  },
  {
    'Id': 4,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Arquitectura',
    'IdEducationLevel': 6,
    'VisibilityOrder': 25,
  },
  {
    'Id': 5,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Bacteriología',
    'IdEducationLevel': 6,
    'VisibilityOrder': 32,
  },
  {
    'Id': 6,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Biología',
    'IdEducationLevel': 6,
    'VisibilityOrder': 34,
  },
  {
    'Id': 7,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Biología marina',
    'IdEducationLevel': 6,
    'VisibilityOrder': 35,
  },
  {
    'Id': 8,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ciencias políticas y gobierno',
    'IdEducationLevel': 6,
    'VisibilityOrder': 36,
  },
  {
    'Id': 9,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Comercio internacional',
    'IdEducationLevel': 6,
    'VisibilityOrder': 37,
  },
  {
    'Id': 10,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Comunicación social y periodismo',
    'IdEducationLevel': 6,
    'VisibilityOrder': 39,
  },
  {
    'Id': 11,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Contaduría',
    'IdEducationLevel': 6,
    'VisibilityOrder': 41,
  },
  {
    'Id': 12,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería de petróleos',
    'IdEducationLevel': 6,
    'VisibilityOrder': 84,
  },
  {
    'Id': 13,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Derecho Abogado',
    'IdEducationLevel': 6,
    'VisibilityOrder': 43,
  },
  {
    'Id': 14,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Diseño de Interiores',
    'IdEducationLevel': 6,
    'VisibilityOrder': 45,
  },
  {
    'Id': 15,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Diseño de modas y patronaje',
    'IdEducationLevel': 6,
    'VisibilityOrder': 47,
  },
  {
    'Id': 16,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Diseño gráfico',
    'IdEducationLevel': 6,
    'VisibilityOrder': 48,
  },
  {
    'Id': 17,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Diseño industrial',
    'IdEducationLevel': 6,
    'VisibilityOrder': 49,
  },
  {
    'Id': 18,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Diseño textil',
    'IdEducationLevel': 7,
    'VisibilityOrder': 50,
  },
  {
    'Id': 19,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Economía',
    'IdEducationLevel': 6,
    'VisibilityOrder': 52,
  },
  {
    'Id': 20,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Enfermería',
    'IdEducationLevel': 6,
    'VisibilityOrder': 53,
  },
  {
    'Id': 21,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Filosofía',
    'IdEducationLevel': 6,
    'VisibilityOrder': 61,
  },
  {
    'Id': 22,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Finanzas Relaciones internacionales y gobierno',
    'IdEducationLevel': 6,
    'VisibilityOrder': 62,
  },
  {
    'Id': 23,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Física',
    'IdEducationLevel': 6,
    'VisibilityOrder': 63,
  },
  {
    'Id': 24,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Fisioterapia',
    'IdEducationLevel': 6,
    'VisibilityOrder': 64,
  },
  {
    'Id': 25,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Fonoaudiología',
    'IdEducationLevel': 6,
    'VisibilityOrder': 67,
  },
  {
    'Id': 26,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería civil',
    'IdEducationLevel': 6,
    'VisibilityOrder': 79,
  },
  {
    'Id': 27,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería de alimentos',
    'IdEducationLevel': 6,
    'VisibilityOrder': 80,
  },
  {
    'Id': 28,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería de producción agroindustrial',
    'IdEducationLevel': 6,
    'VisibilityOrder': 85,
  },
  {
    'Id': 29,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería de sistemas  Computación',
    'IdEducationLevel': 6,
    'VisibilityOrder': 87,
  },
  {
    'Id': 30,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería eléctrica',
    'IdEducationLevel': 6,
    'VisibilityOrder': 90,
  },
  {
    'Id': 31,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería industrial',
    'IdEducationLevel': 6,
    'VisibilityOrder': 94,
  },
  {
    'Id': 32,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería mecánica',
    'IdEducationLevel': 6,
    'VisibilityOrder': 95,
  },
  {
    'Id': 33,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería química',
    'IdEducationLevel': 6,
    'VisibilityOrder': 99,
  },
  {
    'Id': 34,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Matemáticas',
    'IdEducationLevel': 6,
    'VisibilityOrder': 107,
  },
  {
    'Id': 35,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Medicina',
    'IdEducationLevel': 6,
    'VisibilityOrder': 108,
  },
  {
    'Id': 36,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Microbiología',
    'IdEducationLevel': 6,
    'VisibilityOrder': 109,
  },
  {
    'Id': 37,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Preescolar',
    'IdEducationLevel': 7,
    'VisibilityOrder': 122,
  },
  {
    'Id': 38,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Psicología',
    'IdEducationLevel': 6,
    'VisibilityOrder': 127,
  },
  {
    'Id': 39,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Publicidad y mercadeo',
    'IdEducationLevel': 6,
    'VisibilityOrder': 128,
  },
  {
    'Id': 40,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Secretariado',
    'IdEducationLevel': 7,
    'VisibilityOrder': 131,
  },
  {
    'Id': 41,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Sociología',
    'IdEducationLevel': 6,
    'VisibilityOrder': 134,
  },
  {
    'Id': 42,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología de alimentos',
    'IdEducationLevel': 7,
    'VisibilityOrder': 154,
  },
  {
    'Id': 43,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecn Administración de personal',
    'IdEducationLevel': 7,
    'VisibilityOrder': 136,
  },
  {
    'Id': 44,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecn Sistemas  Computación',
    'IdEducationLevel': 7,
    'VisibilityOrder': 146,
  },
  {
    'Id': 45,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecn Relaciones Industriales',
    'IdEducationLevel': 7,
    'VisibilityOrder': 144,
  },
  {
    'Id': 46,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Trabajo social',
    'IdEducationLevel': 6,
    'VisibilityOrder': 158,
  },
  {
    'Id': 47,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Veterinaria',
    'IdEducationLevel': 6,
    'VisibilityOrder': 160,
  },
  {
    'Id': 48,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración de empresas',
    'IdEducationLevel': 6,
    'VisibilityOrder': 6,
  },
  {
    'Id': 49,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Zootecnia',
    'IdEducationLevel': 6,
    'VisibilityOrder': 161,
  },
  {
    'Id': 50,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Otra',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 456,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Acuicultura',
    'IdEducationLevel': 7,
    'VisibilityOrder': 1,
  },
  {
    'Id': 457,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración aeronáutica',
    'IdEducationLevel': 6,
    'VisibilityOrder': 2,
  },
  {
    'Id': 458,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración agropecuaria',
    'IdEducationLevel': 6,
    'VisibilityOrder': 3,
  },
  {
    'Id': 459,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración de aerolíneas',
    'IdEducationLevel': 6,
    'VisibilityOrder': 4,
  },
  {
    'Id': 460,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración de bienes raíces',
    'IdEducationLevel': 6,
    'VisibilityOrder': 5,
  },
  {
    'Id': 461,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración de negocios',
    'IdEducationLevel': 6,
    'VisibilityOrder': 7,
  },
  {
    'Id': 462,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración de obras civiles',
    'IdEducationLevel': 10,
    'VisibilityOrder': 8,
  },
  {
    'Id': 463,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración de personal',
    'IdEducationLevel': 10,
    'VisibilityOrder': 9,
  },
  {
    'Id': 464,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración de seguros',
    'IdEducationLevel': 7,
    'VisibilityOrder': 10,
  },
  {
    'Id': 465,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración de transporte',
    'IdEducationLevel': 7,
    'VisibilityOrder': 13,
  },
  {
    'Id': 466,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración financiera',
    'IdEducationLevel': 6,
    'VisibilityOrder': 14,
  },
  {
    'Id': 467,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración hospitalaria',
    'IdEducationLevel': 6,
    'VisibilityOrder': 15,
  },
  {
    'Id': 468,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración industrial',
    'IdEducationLevel': 7,
    'VisibilityOrder': 16,
  },
  {
    'Id': 469,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración pública',
    'IdEducationLevel': 6,
    'VisibilityOrder': 17,
  },
  {
    'Id': 470,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración tributaria',
    'IdEducationLevel': 10,
    'VisibilityOrder': 18,
  },
  {
    'Id': 472,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Agrología',
    'IdEducationLevel': 7,
    'VisibilityOrder': 21,
  },
  {
    'Id': 473,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Agronomía',
    'IdEducationLevel': 6,
    'VisibilityOrder': 22,
  },
  {
    'Id': 474,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Arqueología',
    'IdEducationLevel': 6,
    'VisibilityOrder': 24,
  },
  {
    'Id': 475,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Arte y decoración',
    'IdEducationLevel': 6,
    'VisibilityOrder': 26,
  },
  {
    'Id': 476,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Artes plásticas',
    'IdEducationLevel': 6,
    'VisibilityOrder': 27,
  },
  {
    'Id': 927,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería electrónica',
    'IdEducationLevel': 6,
    'VisibilityOrder': 92,
  },
  {
    'Id': 2820,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Bibliotecología',
    'IdEducationLevel': 6,
    'VisibilityOrder': 33,
  },
  {
    'Id': 2958,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Odontología',
    'IdEducationLevel': 6,
    'VisibilityOrder': 113,
  },
  {
    'Id': 3573,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería metalúrgica',
    'IdEducationLevel': 6,
    'VisibilityOrder': 97,
  },
  {
    'Id': 3574,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Optometría',
    'IdEducationLevel': 6,
    'VisibilityOrder': 114,
  },
  {
    'Id': 3575,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Terapia respiratoria',
    'IdEducationLevel': 7,
    'VisibilityOrder': 157,
  },
  {
    'Id': 3576,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería catastral  Geodesia',
    'IdEducationLevel': 6,
    'VisibilityOrder': 78,
  },
  {
    'Id': 3577,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Producción Cine  Televisión',
    'IdEducationLevel': 6,
    'VisibilityOrder': 123,
  },
  {
    'Id': 3578,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería ambiental  Forestal',
    'IdEducationLevel': 6,
    'VisibilityOrder': 76,
  },
  {
    'Id': 3579,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Química',
    'IdEducationLevel': 6,
    'VisibilityOrder': 129,
  },
  {
    'Id': 3580,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Química Farmacéutica',
    'IdEducationLevel': 6,
    'VisibilityOrder': 130,
  },
  {
    'Id': 3581,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Oceanografía',
    'IdEducationLevel': 6,
    'VisibilityOrder': 112,
  },
  {
    'Id': 3582,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Música',
    'IdEducationLevel': 6,
    'VisibilityOrder': 110,
  },
  {
    'Id': 5713,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Nutrición y dietética',
    'IdEducationLevel': 6,
    'VisibilityOrder': 111,
  },
  {
    'Id': 6890,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecn En seguros',
    'IdEducationLevel': 7,
    'VisibilityOrder': 139,
  },
  {
    'Id': 6906,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecn Regencia Farmacia',
    'IdEducationLevel': 7,
    'VisibilityOrder': 143,
  },
  {
    'Id': 8816,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecn Química',
    'IdEducationLevel': 7,
    'VisibilityOrder': 142,
  },
  {
    'Id': 9366,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Idiomas Lenguas modernas',
    'IdEducationLevel': 6,
    'VisibilityOrder': 72,
  },
  {
    'Id': 15487,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Hotelería y turismo',
    'IdEducationLevel': 6,
    'VisibilityOrder': 71,
  },
  {
    'Id': 17415,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Geología',
    'IdEducationLevel': 6,
    'VisibilityOrder': 69,
  },
  {
    'Id': 18287,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Geografía',
    'IdEducationLevel': 6,
    'VisibilityOrder': 68,
  },
  {
    'Id': 18288,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Entomología',
    'IdEducationLevel': 6,
    'VisibilityOrder': 54,
  },
  {
    'Id': 18289,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Fitopatología',
    'IdEducationLevel': 7,
    'VisibilityOrder': 66,
  },
  {
    'Id': 18290,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Fitomejoramiento',
    'IdEducationLevel': 7,
    'VisibilityOrder': 65,
  },
  {
    'Id': 19414,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería agrónoma',
    'IdEducationLevel': 6,
    'VisibilityOrder': 75,
  },
  {
    'Id': 22110,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecn Seguridad industrial',
    'IdEducationLevel': 7,
    'VisibilityOrder': 145,
  },
  {
    'Id': 24853,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería de telecomunicaciones',
    'IdEducationLevel': 6,
    'VisibilityOrder': 88,
  },
  {
    'Id': 25302,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería administrativa',
    'IdEducationLevel': 6,
    'VisibilityOrder': 73,
  },
  {
    'Id': 27966,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería de minas',
    'IdEducationLevel': 6,
    'VisibilityOrder': 82,
  },
  {
    'Id': 27967,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingenieria sanitaria',
    'IdEducationLevel': 7,
    'VisibilityOrder': 100,
  },
  {
    'Id': 27968,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Sin Profesión',
    'IdEducationLevel': 11,
    'VisibilityOrder': 133,
  },
  {
    'Id': 27969,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería electromecánica',
    'IdEducationLevel': 6,
    'VisibilityOrder': 91,
  },
  {
    'Id': 28292,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería mecatrónica',
    'IdEducationLevel': 6,
    'VisibilityOrder': 96,
  },
  {
    'Id': 28295,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Terapia ocupacional',
    'IdEducationLevel': 6,
    'VisibilityOrder': 156,
  },
  {
    'Id': 28325,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería de transportes y vías',
    'IdEducationLevel': 7,
    'VisibilityOrder': 89,
  },
  {
    'Id': 28354,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Docente',
    'IdEducationLevel': 6,
    'VisibilityOrder': 51,
  },
  {
    'Id': 28430,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería física',
    'IdEducationLevel': 7,
    'VisibilityOrder': 93,
  },
  {
    'Id': 29060,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Cultura física deporte y recreación',
    'IdEducationLevel': 6,
    'VisibilityOrder': 42,
  },
  {
    'Id': 29349,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería biomédica',
    'IdEducationLevel': 6,
    'VisibilityOrder': 77,
  },
  {
    'Id': 29350,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Comunicación publicitaria',
    'IdEducationLevel': 6,
    'VisibilityOrder': 38,
  },
  {
    'Id': 29351,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración uniempresarial',
    'IdEducationLevel': 6,
    'VisibilityOrder': 20,
  },
  {
    'Id': 29352,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Diseño de la comunicación gráfica',
    'IdEducationLevel': 6,
    'VisibilityOrder': 46,
  },
  {
    'Id': 29353,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería telemática',
    'IdEducationLevel': 7,
    'VisibilityOrder': 101,
  },
  {
    'Id': 29354,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Licenciaturas',
    'IdEducationLevel': 6,
    'VisibilityOrder': 102,
  },
  {
    'Id': 29355,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Historia',
    'IdEducationLevel': 6,
    'VisibilityOrder': 70,
  },
  {
    'Id': 29356,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología en electrónica',
    'IdEducationLevel': 7,
    'VisibilityOrder': 155,
  },
  {
    'Id': 29365,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería de redes y telecomunicaciones',
    'IdEducationLevel': 6,
    'VisibilityOrder': 86,
  },
  {
    'Id': 29366,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería naval',
    'IdEducationLevel': 7,
    'VisibilityOrder': 98,
  },
  {
    'Id': 29367,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecn Mecánico',
    'IdEducationLevel': 7,
    'VisibilityOrder': 140,
  },
  {
    'Id': 29368,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecn Metalmecánico',
    'IdEducationLevel': 7,
    'VisibilityOrder': 141,
  },
  {
    'Id': 29369,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecn Electricista',
    'IdEducationLevel': 7,
    'VisibilityOrder': 137,
  },
  {
    'Id': 29370,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecn Electrónico',
    'IdEducationLevel': 7,
    'VisibilityOrder': 138,
  },
  {
    'Id': 29371,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Literatura',
    'IdEducationLevel': 6,
    'VisibilityOrder': 103,
  },
  {
    'Id': 29372,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Construcción',
    'IdEducationLevel': 6,
    'VisibilityOrder': 40,
  },
  {
    'Id': 29373,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración de sistemas informáticos',
    'IdEducationLevel': 7,
    'VisibilityOrder': 12,
  },
  {
    'Id': 29379,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Profesional en Gastronomía',
    'IdEducationLevel': 6,
    'VisibilityOrder': 124,
  },
  {
    'Id': 29380,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Profesional en logística',
    'IdEducationLevel': 6,
    'VisibilityOrder': 125,
  },
  {
    'Id': 29381,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Técnico en desarrollo y mantenimiento de software',
    'IdEducationLevel': 7,
    'VisibilityOrder': 148,
  },
  {
    'Id': 29382,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería de Mercados',
    'IdEducationLevel': 7,
    'VisibilityOrder': 81,
  },
  {
    'Id': 29383,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Estadista',
    'IdEducationLevel': 6,
    'VisibilityOrder': 58,
  },
  {
    'Id': 29384,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería Aeronáutica',
    'IdEducationLevel': 6,
    'VisibilityOrder': 74,
  },
  {
    'Id': 29385,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería de Motores',
    'IdEducationLevel': 7,
    'VisibilityOrder': 83,
  },
  {
    'Id': 29386,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Técnico de Mantenimiento',
    'IdEducationLevel': 7,
    'VisibilityOrder': 147,
  },
  {
    'Id': 29387,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Piloto',
    'IdEducationLevel': 6,
    'VisibilityOrder': 121,
  },
  {
    'Id': 29388,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Auxiliar de Vuelo',
    'IdEducationLevel': 7,
    'VisibilityOrder': 28,
  },
  {
    'Id': 29389,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Despachador',
    'IdEducationLevel': 7,
    'VisibilityOrder': 44,
  },
  {
    'Id': 29390,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Estadístico',
    'IdEducationLevel': 6,
    'VisibilityOrder': 60,
  },
  {
    'Id': 29391,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Técnico en Gestión Contable',
    'IdEducationLevel': 7,
    'VisibilityOrder': 149,
  },
  {
    'Id': 29392,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Técnico en Gestión Empresarial',
    'IdEducationLevel': 7,
    'VisibilityOrder': 150,
  },
  {
    'Id': 29393,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Técnico en Logística',
    'IdEducationLevel': 7,
    'VisibilityOrder': 151,
  },
  {
    'Id': 29394,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Estadística',
    'IdEducationLevel': 6,
    'VisibilityOrder': 59,
  },
  {
    'Id': 29395,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Técnico en salud ocupacional',
    'IdEducationLevel': 6,
    'VisibilityOrder': 153,
  },
  {
    'Id': 29396,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Técnico en radiología e imágenes diagnosticas',
    'IdEducationLevel': 7,
    'VisibilityOrder': 152,
  },
  {
    'Id': 29397,
    'IsUndefinedValue': true,
    'DeletedKey': 29397,
    'Name': 'Sin Definir',
    'IdEducationLevel': 11,
    'VisibilityOrder': 132,
  },
  {
    'Id': 101235134,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Bachillerato Académico',
    'IdEducationLevel': 9,
    'VisibilityOrder': 29,
  },
  {
    'Id': 101235135,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Bachillerato Comercial',
    'IdEducationLevel': 9,
    'VisibilityOrder': 30,
  },
  {
    'Id': 101235136,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Bachillerato Técnico',
    'IdEducationLevel': 9,
    'VisibilityOrder': 31,
  },
  {
    'Id': 101235137,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Maestría en Administración de Empresa',
    'IdEducationLevel': 6,
    'VisibilityOrder': 104,
  },
  {
    'Id': 101235138,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Maestría en Ingeniería Industrial',
    'IdEducationLevel': 6,
    'VisibilityOrder': 106,
  },
  {
    'Id': 101235139,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Maestría en economía',
    'IdEducationLevel': 6,
    'VisibilityOrder': 105,
  },
  {
    'Id': 101235140,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Otra Maestría',
    'IdEducationLevel': 6,
    'VisibilityOrder': 117,
  },
  {
    'Id': 101235141,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización en Administración de Empresas',
    'IdEducationLevel': 6,
    'VisibilityOrder': 55,
  },
  {
    'Id': 101235142,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización en Mercadeo',
    'IdEducationLevel': 6,
    'VisibilityOrder': 57,
  },
  {
    'Id': 101235144,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización en Finanzas',
    'IdEducationLevel': 6,
    'VisibilityOrder': 56,
  },
  {
    'Id': 101235145,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Otra Especialización',
    'IdEducationLevel': 6,
    'VisibilityOrder': 116,
  },
  {
    'Id': 101235146,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ph D',
    'IdEducationLevel': 6,
    'VisibilityOrder': 120,
  },
  {
    'Id': 145529384,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Otros',
    'IdEducationLevel': 10,
    'VisibilityOrder': 118,
  },
  {
    'Id': 1944809867,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tubero',
    'IdEducationLevel': 7,
    'VisibilityOrder': 159,
  },
  {
    'Id': 1944809868,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Pailero',
    'IdEducationLevel': 7,
    'VisibilityOrder': 119,
  },
  {
    'Id': 1944809869,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Soldador',
    'IdEducationLevel': 7,
    'VisibilityOrder': 135,
  },
  {
    'Id': 1944809870,
    'IsUndefinedValue': false,
    'DeletedKey': 1944809870,
    'Name': 'Prueba',
    'IdEducationLevel': 12,
    'VisibilityOrder': 126,
  },
  {
    'Id': 1944809871,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Conservación y Restauración del Patrimonio Cultural Mueble',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809872,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Estética y Cosmetología',
    'IdEducationLevel': 10,
    'VisibilityOrder': 162,
  },
  {
    'Id': 1944809873,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Mecánica  Mant Automotriz',
    'IdEducationLevel': 10,
    'VisibilityOrder': 163,
  },
  {
    'Id': 1944809874,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Investigación Judicial y Criminalística',
    'IdEducationLevel': 10,
    'VisibilityOrder': 164,
  },
  {
    'Id': 1944809875,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Pastelería Repostería y Panadería',
    'IdEducationLevel': 15,
    'VisibilityOrder': 165,
  },
  {
    'Id': 1944809876,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Mesa y Bar',
    'IdEducationLevel': 15,
    'VisibilityOrder': 166,
  },
  {
    'Id': 1944809877,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Gastronomía Culinaria o Cocina',
    'IdEducationLevel': 6,
    'VisibilityOrder': 167,
  },
  {
    'Id': 1944809878,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología en Gestión Administrativa',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809879,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Negocios Internacionales',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809880,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería de diseño de producto',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809881,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Doctorado en economía',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809882,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Gobierno y Relaciones Internacionales',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809883,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería de producción',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809884,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Mercadeo',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809885,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería de procesos',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809886,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Doctorado en administración',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809887,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Doctorado en humanidades',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809888,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización en gerencia de proyectos',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809889,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Maestría en mercadeo',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809890,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Maestría en desarrollo humano',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809891,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Maestría en derecho',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809892,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Otro Doctorado',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809893,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración Agroindustrial',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809894,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Licenciatura en Educación Básica',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809895,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Licenciatura en Español y Literatura',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809896,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Licenciatura en Inglés ',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809897,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Técnica Profesional en Producción ',
    'IdEducationLevel': 7,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809898,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Agropecuaria',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809901,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología Agroindustrial',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809902,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización en gestión de servicios de tecnologías de información',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809903,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización en proyectos de desarrollo',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809904,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización en pedagogía',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809905,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización en edumatica',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809906,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización en derecho penal',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809907,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización en gestión integral del riesgo de desastres',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809908,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Estudios y gestión Cultural',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809910,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Gestión documental ',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809911,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Auxiliar archivo',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809912,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Finanzas y Gobierno',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809913,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Maestría en Finanzas Corporativas',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809914,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Maestría en Dirección de Marketing',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809915,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Maestría en Emprendimiento e Innovación',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809917,
    'IsUndefinedValue': false,
    'DeletedKey': 1944809917,
    'Name': 'Otra',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809918,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería de Energías',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809919,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Maestría en Ingeniería de Yacimientos',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809920,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización en Gerencia de la Calidad',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809921,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización en Gerencia de Empresas Constructoras',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809922,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización en Gerencia del Talento Humano',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809923,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización en Gestión Ambiental',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809924,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización en Negocios Internacionales e Integración Económica',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809925,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización en Planeación Territorial',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809926,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Maestría en Planeación Territorial',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809927,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Maestría en Gestión Integral de la Calidad y la Productividad',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809928,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Maestría en Gestión Ambiental para la Competitividad',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809929,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería Automotriz',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809930,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería Textil',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809931,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización En Educación Bilingüe',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809932,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización En Gerencia De La Salud Ocupacional',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809933,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización En Administración De Servicios De Salud',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809934,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización En Alta Gerencia',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809935,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización En Audiología',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809936,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización En Salud Pública',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809937,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización En Atención Integral A La Primera Infancia',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809938,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización En Gerencia Tributaria',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809939,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización En Microbiología Ambiental',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809940,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización En Planeación Urbana',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809941,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización En Construcción Sostenible',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809942,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización En Gerencia Prospectiva Y Estratégica',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809943,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización En Gerencia Logística Internacional',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809944,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización Valoración Inmobiliaria',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809945,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Especialización En Legislación Aduanera',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809946,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Banca Y Finanzas',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809947,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Operación Y Mantenimiento Electromecánico',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809948,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Levantamientos Topográficos',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809949,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Manejo De Recursos Ambientales',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809950,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Electricidad Industrial',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809951,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Estudios Geotécnicos',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809952,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Implementación De Sistemas Electrónicos Industriales',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809953,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Gestión De Sistemas De Telecomunicaciones',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809954,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Desarrollo De Sistemas Informáticos',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809955,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Producción Industrial',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809956,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Gestión Comercial',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809957,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Gestión Comunitaria',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809958,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnologia En Electromedicina',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809959,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Gestión De Servicios Gastronómicos',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809960,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Gestión Turística',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809961,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Delineante De Arquitectura E Ingeniería',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809962,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Gestión Ambiental',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809963,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Gestión Catastral',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809964,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Gestión De Mercadeo',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809965,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Tecnología En Comercio Internacional',
    'IdEducationLevel': 10,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809966,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Profesional En Marketing Y Negocios Internacionales',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809967,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingenierìa De Software',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809968,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Ingeniería Comercial',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809969,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Biotecnología',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809970,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Planeación Y Desarrollo Social',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809971,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Construcciones Civiles',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809972,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Administración Comercial Y De Mercadeo',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809973,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Licenciatura En Bilingüismo',
    'IdEducationLevel': 6,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809974,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Técnico Profesional En Salud Oral',
    'IdEducationLevel': 7,
    'VisibilityOrder': 0,
  },
  {
    'Id': 1944809975,
    'IsUndefinedValue': false,
    'DeletedKey': null,
    'Name': 'Técnico Profesional En Mecanica Dental',
    'IdEducationLevel': 7,
    'VisibilityOrder': 0,
  },

];

const SelectProfessions = () => {

  return (
    <Autocomplete
      id='Professions'
      options={profession}
      getOptionLabel={option => option.Name}
      style={{ width: 350, marginLeft: 260, marginTop: 200, float: 'left' }}
      renderInput={params => <TextField {...params} label='Profesiones' variant='outlined' />}
      onChange={(event, newValue) => {
        handleInput(newValue, 'professions');
      }}

    />
  );
};

export default SelectProfessions;
