/* eslint-disable no-multi-spaces */
/* eslint-disable no-use-before-define */
import React from 'react';
import TextField from '@material-ui/core/TextField';
import Autocomplete from '@material-ui/lab/Autocomplete';
import handleInput from '../hooks/status';
// import { makeStyles } from '@material-ui/core/styles';
// import styles from '../assets/styles/components/Selection.scss'

const SelectCity = () => {

  return (
    <Autocomplete
      id='Country'
      options={Cities}
      getOptionLabel={option => option.Name}
      style={{ width: 350, marginTop: 20, marginLeft: 260, paddingBlock: 10, float: 'left' }}
      renderInput={params => <TextField {...params} label='Cuidad' variant='outlined' />}
      onChange={(event, newValue) => {
        handleInput(newValue, 'city');
      }}

    />
  );
};

const Cities = [

  {
    'Id': 1,
    'Culture': '-',
    'IsUndefinedValue': true,
    'PhonePrefix': '0',
    'Name': 'Sin definir',
    'DeletedKey': 1,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 2,
    'Culture': 'es-AR',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Argentina',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 3,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Australia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 4,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Austria',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 5,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Bélgica',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 6,
    'Culture': 'es-BO',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Bolivia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 7,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Brasil',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 8,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Camboya',
    'DeletedKey': 8,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 9,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Canadá',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 10,
    'Culture': 'es-CL',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Chile',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 11,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'China',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 12,
    'Culture': 'es-CO',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Colombia',
    'DeletedKey': null,
    'Longitude': '-74,297333',
    'Latitude': '4,570868',
  },
  {
    'Id': 13,
    'Culture': 'es-CR',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Costa Rica',
    'DeletedKey': null,
    'Longitude': '-84,083333',
    'Latitude': '9,933333',
  },
  {
    'Id': 14,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Corea del Sur',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 15,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Cuba',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 16,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Curacao',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 17,
    'Culture': '--',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Alemania',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 18,
    'Culture': 'es-DO',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'República Dominicana',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 19,
    'Culture': 'es-EC',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Ecuador',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 20,
    'Culture': 'es-ES',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'España',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 21,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Francia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 22,
    'Culture': 'Inglés',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Inglaterra',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 23,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Guinea-Ecuatorial',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 24,
    'Culture': 'es-GT',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Guatemala',
    'DeletedKey': null,
    'Longitude': '-90,550000',
    'Latitude': '14,633333',
  },
  {
    'Id': 25,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Hong Kong',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 26,
    'Culture': 'es-HN',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Honduras',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 27,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Holanda',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 28,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Haití',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 29,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Hungría',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 30,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Islas Comores',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 31,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'India',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 32,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Irlanda',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 33,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Israel',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 34,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Italia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 35,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Jamaica',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 36,
    'Culture': '--',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Japón',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 37,
    'Culture': 'es-MX',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'México',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 38,
    'Culture': 'es-NI',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Nicaragua',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 39,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Noruega',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 40,
    'Culture': 'es-PA',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Panamá',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 41,
    'Culture': 'es-PE',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Perú',
    'DeletedKey': null,
    'Longitude': '-77,016667',
    'Latitude': '-10,033333',
  },
  {
    'Id': 42,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Polonia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 43,
    'Culture': 'es-PR',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Puerto Rico',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 44,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Portugal',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 45,
    'Culture': 'es-PY',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Paraguay',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 46,
    'Culture': 'es-SV',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'El Salvador',
    'DeletedKey': null,
    'Longitude': '-89,166667',
    'Latitude': '13,666667',
  },
  {
    'Id': 47,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Suecia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 48,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Suiza',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 49,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Trinidad y Tobago',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 50,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Turquía',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 51,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Ucrania',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 52,
    'Culture': 'es-UY',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Uruguay',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 53,
    'Culture': 'en-US',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Estados Unidos',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 54,
    'Culture': 'es-VE',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Venezuela',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101123022,
    'Culture': 'Danes',
    'IsUndefinedValue': false,
    'PhonePrefix': '00',
    'Name': 'Dinamarca',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101124024,
    'Culture': 'Hungar',
    'IsUndefinedValue': false,
    'PhonePrefix': '00',
    'Name': 'Nueva Zelanda',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101124025,
    'Culture': 'Ruso',
    'IsUndefinedValue': false,
    'PhonePrefix': '00',
    'Name': 'Rusia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101124026,
    'Culture': 'Inglés',
    'IsUndefinedValue': false,
    'PhonePrefix': '00',
    'Name': 'Escocia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101135034,
    'Culture': '-',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Gondwana',
    'DeletedKey': 101135034,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101184083,
    'Culture': 'ne-dut',
    'IsUndefinedValue': false,
    'PhonePrefix': '297',
    'Name': 'Aruba',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101231130,
    'Culture': 'eslove',
    'IsUndefinedValue': false,
    'PhonePrefix': '00',
    'Name': 'Eslovenia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101231131,
    'Culture': 'Lituan',
    'IsUndefinedValue': false,
    'PhonePrefix': '00',
    'Name': 'Lituania',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383282,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Abjasia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383283,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Acrotiri y Dhekelia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383284,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Afganistán',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383285,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Albania',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383286,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Andorra',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383287,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Angola',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383288,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Anguila',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383289,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Antigua y Barbuda',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383293,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Argelia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383294,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Armenia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383295,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Azerbaiyán',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383296,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Bahamas',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383297,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Baréin',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383298,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Bangladés',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383299,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Barbados',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383300,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Belice',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383301,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Benín',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383302,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Bermudas',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383303,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Bielorrusia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383304,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Birmania',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383305,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Bosnia y Herzegovina',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383306,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Botsuana',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383307,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Brunéi',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383308,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Bulgaria',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383309,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Burkina Faso',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383310,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Burundi',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383311,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Bután',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383312,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Cabo Verde',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383313,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Caimán, islas',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383314,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Camboya',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383315,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Camerún',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383316,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Catar',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383317,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Centroafricana, Rep. ',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383318,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Chad',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383319,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Checa, Rep.',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383320,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Chipre',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383321,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Chipre, RTN',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383322,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Cocos, islas',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383323,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Rep. Del Congo',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383324,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Rep.Dem. Del Congo',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383325,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Cook, Islas ',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383326,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Corea del Norte',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383327,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Costa de Marfil',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383328,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Croacia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383329,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Dominica',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383330,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Dominicana, Rep. ',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383331,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Egipto',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383333,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Eritrea ',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383334,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Eslovaquia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383335,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Estonia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383336,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Etiopía',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383337,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Feroe, Islas',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383338,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Filipinas',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383339,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Finlandia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383340,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Fiyi',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383341,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Gabón',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383342,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Gambia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383343,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Georgia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383344,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Ghana',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383345,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Gibraltar',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383346,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Granada',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383347,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Grecia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383348,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Groenlandia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383349,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Guam',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383350,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Guernsey',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383351,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Guinea',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383352,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Guinea - Bissau',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383353,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Guyana',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383354,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Indonesia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383356,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Irak',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383359,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Islandia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383360,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Jersey',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383362,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Kazajistán',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383363,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Kenia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383364,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Kirguistán',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383365,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Kiribati',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383366,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Kosovo',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383368,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Laos',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383369,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Lesoto',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383370,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Letonia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383372,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Liberia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383373,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Libia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383374,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Liechtenstein',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383376,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Luxemburgo',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383377,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Macao',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383378,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Macedonia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383379,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Madagascar',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383380,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Malasia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383381,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Malaui',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383382,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Maldivas',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383383,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Malí',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383384,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Malta',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383385,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Malvinas, Islas',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383386,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Man, islas',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383387,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Marianas del Norte, Islas',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383388,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Marruecos',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383389,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Marshall, Islas',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383390,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Mauricio',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383391,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Mauritania',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383392,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Micronesia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383393,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Moldavia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383394,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Mónaco',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383395,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Mongolia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383396,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Montenegro',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383397,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Montserrat',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383398,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Mozambique',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383399,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Nagorno Karabaj',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383400,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Namibia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383401,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Nauru',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383402,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Navidad, Isla ',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383403,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Nepal',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383404,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Níger',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383405,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Nigeria',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383406,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Niue',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383407,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Norfolk, Isla',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383408,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Nueva Caledonia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383411,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Osetia del Sur',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383412,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Países Bajos',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383413,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Pakistán',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383414,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Palaos',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383415,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Palestina',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383416,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Papúa Nueva Guinea',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383417,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Pitcaim, Islas ',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383418,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Polinesia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383419,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Reino Unido',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383420,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Ruanda',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383421,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Rumania',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383422,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Sahara Occidental',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383423,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Salomón, Islas',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383424,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Samoa',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383425,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Samoa Americana',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101383426,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'San Bartolomé',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386285,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'San Marino',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386286,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'San Martín (Francia)',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386287,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'San Martín (Países Bajos)',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386288,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'San Pedro y Miquelón',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386289,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'San Vicente y las Granadinas',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386290,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Santa Elena, Ascensión y Tristán de Acuña',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386291,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Santa Lucía',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386292,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Santo Tomé y Príncipe',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386293,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Senegal',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386294,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Serbia ',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386295,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Seychelles',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386296,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Sierra Leona',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386297,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Singapur',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386299,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Somalia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386300,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Somalilandia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386302,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Sri Lanka',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386303,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Suazilandia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386304,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Sudáfrica',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386305,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Sudán',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386306,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Sudán del Sur',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386307,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Surinam',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386308,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Svalbard',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386309,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Tailandia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386310,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Taiwán',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386311,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Tanzania',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386312,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Tayikistán',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386313,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Timor Oriental',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386314,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Togo',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386315,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Tokelau',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386316,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Tonga',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386317,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Transnistria',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386318,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Túnez',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386319,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Turcas y Caicos, Islas',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386320,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Turkmenistán',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386321,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Tuvalu',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386322,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Uganda',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386323,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Uzbekistán',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386324,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Vanuatu',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386325,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Ciudad del  Vaticano',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386326,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Vietnam',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386327,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Islas Vírgenes Británicas',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386328,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Islas Vírgenes de los Estados Unidos',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386329,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Wallis y Futuna',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386331,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Yibuti',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386332,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Zambia',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386333,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Zimbabue',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101386334,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'Irán',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
  {
    'Id': 101408307,
    'Culture': '0',
    'IsUndefinedValue': false,
    'PhonePrefix': '0',
    'Name': 'San Cristóbal y Nieves',
    'DeletedKey': null,
    'Longitude': null,
    'Latitude': null,
  },
];

export default  SelectCity;
